version: '3'

services:
  bank:
    build:
      context: ./bank
      dockerfile: Dockerfile
    container_name: bank-server
    ports:
      - "8080:8080"
    volumes:
      - bank-data:/app/data
      - ./bank:/app
    environment:
      - DB_PATH=/app/data/bank.db
    networks:
      - payment-network
    restart: unless-stopped
    command: python main.py

  client1:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-server-1
    ports:
      - "5001:5001"
    environment:
      - BANK_SERVER_URL=http://bank:8080
      - CLIENT_PORT=5001
      - CLIENT_ID=client1
    networks:
      - payment-network
    depends_on:
      - bank
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: python main.py --mode server

  client2:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-server-2
    ports:
      - "5002:5001"
    environment:
      - BANK_SERVER_URL=http://bank:8080
      - CLIENT_PORT=5001
      - CLIENT_ID=client2
    networks:
      - payment-network
    depends_on:
      - bank
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: python main.py --mode server

networks:
  payment-network:
    driver: bridge

volumes:
  bank-data:
    driver: local 